server:
  port: 8084

spring:
  application:
    name: promotion-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/promotion_db
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/promotion_db
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/tienda}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/tienda/protocol/openid-connect/certs}