server:
  port: 8084

spring:
  application:
    name: promotion-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/promotion_db
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/promotion_db
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml