server:
  port: 8083

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/tienda}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/tienda/protocol/openid-connect/certs}

services:
  carrito-service:
    url: http://carrito-service:8082