server:
  port: 8082

spring:
  application:
    name: carrito-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/carrito_db
    username: postgres
    password: admin123
  liquibase:
    url: jdbc:postgresql://localhost:5432/carrito_db
    user: postgres
    password: admin123
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/tienda}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/tienda/protocol/openid-connect/certs}

services:
  product-service:
    url: http://product-service:8081