server:
  port: 8081

spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/product_db
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml

services:
  promotion-service:
    url: http://promotion-service:8084